name: restpoint
version: 0.0.1
author: Axel Christ <adracus@gmail.com>
description: Develop rest interfaces like a breeze
homepage: https://github.com/Adracus/restpoint
documentation: https://github.com/Adracus/restpoint
dependencies:
  http: any
  mock: any
dev_dependencies:
  unittest: any
